baseURL = 'https://sanmayshelat.github.io/'
languageCode = 'en-us'
title = 'Sanmay Shelat'
theme = 'archie'

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
mode="toggle" # color-mode → light,dark,toggle or auto
useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
mathjax = false # enable MathJax support
katex = true # enable KaTeX support

subtitle = "Data Scientist with a PhD in Behavioural Economics, specializing in applied econometrics, causal inference, and experimentation."
favicon = "img/favicon-photo.ico"



# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/sanmayshelat"

[[params.social]]
name = "Google Scholar"
icon = "folder"
url = "https://scholar.google.com/citations?hl=en&user=sTzpvr8AAAAJ&view_op=list_works&sortby=pubdate"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/sanmayshelat/"

[[params.social]]
name = "CV"
icon = "download"
url = "uploads/Sanmay Shelat Resume.pdf"


[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3